// app/layout.tsx
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemProvider";
import NavigationMenuWithActiveItem from "@/components/navigation-menu-05";
import ClientWrapper from "./Components/ClientWrapper"; // 👈 You’ll create this
import * as motion from "motion/react-client"

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${roboto.variable} font-roboto antialiased w-full`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ClientWrapper>
          <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0, duration: 0.4 }}
          className="sticky top-0 bg-background z-50"
        >
          <NavigationMenuWithActiveItem />
          </motion.div>
            {children}
          </ClientWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
