import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import NavigationMenuWithActiveItem from "@/components/navigation-menu-05";
import * as motion from "motion/react-client"
import { ThemeProvider } from "@/components/ThemProvider";
const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${roboto.variable} font-roboto  antialiased md:px-40 px-5 py-4`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <motion.div
          initial={{ opacity: 0}}
          animate={{ opacity: 1 }}
          transition={{ delay: 0, duration: 0.4 }}
          className="sticky top-0 bg-background"
          >
            <NavigationMenuWithActiveItem/>
        </motion.div>
        { children}
        </ThemeProvider>
      </body>
    </html>
  );
}
